### 1. Baseline (mean prediction)
### 2. Data Cleaning & Preparation
### 3. Linear Regression Model
### 4. Feature Engineering
### 5. Tuning
### 6. Cross-Validation
### 7. Residual Analysis

In [32]:
import pandas as pd
import numpy as np
from math import sqrt
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

In [33]:
data = {
    'StudyHours': [2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Attendance': [60, 65, 70, 72, 75, 80, 85, 88, 90],
    'PrevScore': [40, 45, 50, 55, 60, 65, 70, 75, 80],
    'FinalMarks': [50, 55, 60, 65, 70, 75, 78, 85, 88]
}
df = pd.DataFrame(data)
df

   StudyHours  Attendance  PrevScore  FinalMarks
0           2          60         40          50
1           3          65         45          55
2           4          70         50          60
3           5          72         55          65
4           6          75         60          70
5           7          80         65          75
6           8          85         70          78
7           9          88         75          85
8          10          90         80          88

In [34]:
y=df['FinalMarks'] #output
y

0    50
1    55
2    60
3    65
4    70
5    75
6    78
7    85
8    88
Name: FinalMarks, dtype: int64

In [35]:
# Baseline model
y_pred_baseline = np.repeat(y.mean(), len(y))

# 🔹 Step by Step

# y.mean()
# Calculates the average value of your target variable y.

# len(y)
# Counts how many data points you have.

# np.repeat(y.mean(), len(y))
# Creates an array where every prediction is the same: the mean of y, repeated for all data points.

# 🔹 Purpose

# This is called a baseline model.
# It’s the simplest possible prediction: always predict the average.
# You can then compare your actual regression model to this baseline to see if it’s actually learning something useful.

# Plain English:
# “Predict the average value for every row. This is the simplest benchmark to measure model performance.”

In [36]:
# Calculate metrics
mae = mean_absolute_error(y, y_pred_baseline)
mse = mean_squared_error(y, y_pred_baseline)
rmse = np.sqrt(mse)
r2 = r2_score(y, y_pred_baseline)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R²:", r2)

MAE: 10.716049382716049
MSE: 154.02469135802468
RMSE: 12.410668449282847
R²: 0.0

In [37]:
#clean the data
print(df.isnull().sum())

StudyHours    0
Attendance    0
PrevScore     0
FinalMarks    0
dtype: int64

In [38]:
df=df.fillna(df.mean())
df

   StudyHours  Attendance  PrevScore  FinalMarks
0           2          60         40          50
1           3          65         45          55
2           4          70         50          60
3           5          72         55          65
4           6          75         60          70
5           7          80         65          75
6           8          85         70          78
7           9          88         75          85
8          10          90         80          88

In [39]:
# splitting the data
X=df[['StudyHours','Attendance','PrevScore']] #input exp
y=df['FinalMarks'] #output
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [40]:
# Create the model
model=LinearRegression()

# Train the model
model.fit(X,y)

LinearRegression()

In [41]:
# Prediction: predict on the same data
y_pred = model.predict(X_test)
print(y_pred)

[83.94517091 55.15095205 74.35352145]

In [42]:
# Calculate metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R²:", r2)

MAE: 0.6174198975300152
MSE: 0.5177951485512725
RMSE: 0.7195798416793459
R²: 0.9966713169021704

## Exercise

#### 1. Baseline (mean prediction)
#### 2. Data Cleaning & Preparation
#### 3. Linear Regression Model
#### 4. Calculate MAE, RMSE, R-squared
#### Dataset as follows:

In [69]:
data = {
    'Area': [850, 900, 1000, 1100, 1200, 1500, 1600, 1800, 2000],
    'Bedrooms': [1, 2, 2, 2, 3, 3, 2, 4, 4],
    'Age': [1, 1, 3, 2, 1, 2, 2, 1, 2],
    'Price_in_100K': [5, 6, 7, 7, 7, 9, 9, 11, None]
}

df = pd.DataFrame(data)
print(df)

   Area  Bedrooms  Age  Price_in_100K
0   850         1    1            5.0
1   900         2    1            6.0
2  1000         2    3            7.0
3  1100         2    2            7.0
4  1200         3    1            7.0
5  1500         3    2            9.0
6  1600         2    2            9.0
7  1800         4    1           11.0
8  2000         4    2            NaN

In [70]:
y=df['Price_in_100K']
y

0     5.0
1     6.0
2     7.0
3     7.0
4     7.0
5     9.0
6     9.0
7    11.0
8     NaN
Name: Price_in_100K, dtype: float64

In [71]:
# Baseline model
y_pred_baseline = np.repeat(y.mean(), len(y))
y_pred_baseline

array([7.625, 7.625, 7.625, 7.625, 7.625, 7.625, 7.625, 7.625, 7.625])

In [72]:
df=df.fillna(df.mean())
df

   Area  Bedrooms  Age  Price_in_100K
0   850         1    1          5.000
1   900         2    1          6.000
2  1000         2    3          7.000
3  1100         2    2          7.000
4  1200         3    1          7.000
5  1500         3    2          9.000
6  1600         2    2          9.000
7  1800         4    1         11.000
8  2000         4    2          7.625

In [73]:
#clean the data
print(df.isnull().sum())

Area             0
Bedrooms         0
Age              0
Price_in_100K    0
dtype: int64

In [74]:
# splitting the data
X=df[['Area','Bedrooms','Age']] #input exp
y=df['Price_in_100K'] #output
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [75]:
# Create the model
model=LinearRegression()

# Train the model
model.fit(X,y)

LinearRegression()

In [76]:
# Prediction: predict on the same data
y_pred = model.predict(X_test)
print(y_pred)

[9.29205827 6.23989662 8.25775376]

In [77]:
# Calculate metrics
mae = mean_absolute_error(y, y_pred_baseline)
mse = mean_squared_error(y, y_pred_baseline)
rmse = np.sqrt(mse)
r2 = r2_score(y, y_pred_baseline)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R²:", r2)

MAE: 1.3611111111111112
MSE: 2.875
RMSE: 1.695582495781317
R²: 0.0