# Supervised Machine Learning
## Linear Regression

In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import numpy as np

In [2]:
data = pd.read_csv("sales_data.csv")
data.head()

   Advertising_Spend  Sales_Revenue
0               1000          12000
1               1500          15000
2               2000          18000
3               2500          20000
4               3000          23000

In [26]:
X = data[['Advertising_Spend']]
y = data['Sales_Revenue']

In [27]:
model = LinearRegression()   # create the model
model.fit(X, y)              # train the model

LinearRegression()

In [28]:
new_spend = int(input('Enter New Spend to Predict Sales Revenue'))
predicted_revenue = model.predict([[new_spend]])
print(f'New Spend {new_spend} Predicted Revenue {predicted_revenue}')

Enter New Spend to Predict Sales Revenue 456

New Spend 456 Predicted Revenue [9484.85714286]

C:\Users\haida\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

### Example

In [36]:
#import the required libraries
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [37]:
df = pd.read_csv('sales_data.csv')

In [38]:
df

   Advertising_Spend  Sales_Revenue
0               1000          12000
1               1500          15000
2               2000          18000
3               2500          20000
4               3000          23000
5               3500          25000
6               4000          28000

In [39]:
adv_spend=df[['Advertising_Spend']]
sales_rev=df['Sales_Revenue']

In [40]:
model = LinearRegression()

In [41]:
model.fit(adv_spend, sales_rev)

LinearRegression()

In [42]:
# Step 7: Make predictions
pr_value = model.predict([[2700]])
print(pr_value)

[21185.71428571]

C:\Users\haida\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

### Exercise
##### Linear Regression House Price Prediction
    # Downaload house_price.csv file from gitHub¶
    # Goal: Train a Linear Regression model to predict house price from size.

In [56]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import numpy as np

# Load dataset
df = pd.read_csv('house_price.csv')
df

   Size_sqft   Price
0       1000  150000
1       1200  170000
2       1500  200000
3       1800  230000
4       2000  260000
5       1700       ?

In [58]:
# Replace "?" with actual NaN
df.replace('?', np.nan, inplace=True)

In [59]:
df=df.dropna()
print('Dataset after dropna()')
df

Dataset after dropna()

   Size_sqft   Price
0       1000  150000
1       1200  170000
2       1500  200000
3       1800  230000
4       2000  260000

In [60]:
X = df[['Size_sqft']]
y = df['Price']

In [61]:
model = LinearRegression()
model.fit(X,y)

LinearRegression()

In [62]:
# Step 7: Make predictions
pr_price = model.predict([[1700]])
print(pr_price)

[223470.58823529]

C:\Users\haida\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(