## Logistic Regression - Pass / Fail

In [76]:
#imported all required lib
import pandas as pd
import numpy as np
from sklearn.linear_model import  LogisticRegression

In [77]:
df = pd.read_csv("pass_fail.csv")
df

   Hours Result
0      1   Fail
1      2   Fail
2      3   Fail
3      4   Pass
4      5   Pass
5      6   Pass
6      7   Pass

In [78]:
X = df[['Hours']]
y = df['Result']

In [79]:
model = LogisticRegression()

In [80]:
model.fit(X,y)

LogisticRegression()

In [81]:
# Step 7: Make predictions
pred_35 = model.predict([[3.5]])
print('Predicted result for 3.5 hours:',pred_35[0])

Predicted result for 3.5 hours: Pass

C:\Users\haida\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [82]:
hours_study=float(input('Number of Hours studied'))
pred_value=model.predict([[hours_study]])
print(f'After {hours_study} hours study you are likely to {pred_value[0]}')

Number of Hours studied 3

After 3.0 hours study you are likely to Fail

C:\Users\haida\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [84]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("customer_purchase.csv")
df

   Age  Salary Purchased
0   22   25000        No
1   25   30000        No
2   30   40000       Yes
3   35   50000       Yes
4   40   60000       Yes

In [85]:
le = LabelEncoder() 
df['Purchased'] = le.fit_transform(df['Purchased'])

X = df[['Age','Salary']]
y = df['Purchased']
df

   Age  Salary  Purchased
0   22   25000          0
1   25   30000          0
2   30   40000          1
3   35   50000          1
4   40   60000          1

In [86]:
model = LogisticRegression()
model.fit(X,y)

LogisticRegression()

In [87]:
# Closing One
#predict the result
new_customer = [[28, 35000]]        #Enter [[age, salary]]
prediction = model.predict(new_customer)
print(f"Predicted Result (1=Yes, 0=No): {prediction[0]}")

Predicted Result (1=Yes, 0=No): 1

C:\Users\haida\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [50]:
# closing Two
new_cust_age = int(input('Enter Age: '))
new_cust_sal = int(input('Enter Salary: '))
new_cust = [[new_cust_age, new_cust_sal]]

prediction = model.predict(new_cust)

if prediction:                    # [0] == 1
    print('Likely Purchased')
else:
    print('Likely Not Purchased')

Enter Age:  40
Enter Salary:  60000

Likely Purchased

C:\Users\haida\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

#### Logistic Regression — Spam/NotSpam
#### Download spam_data.csv from https://www.kaggle.com/
#### Load the Data
#### Do the data cleaning and labeling (if required)
#### Use Logistic Regression Algorithm to trained the Model
#### Predict Result if the email is spam or not spam

In [101]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer

df = pd.read_csv("spam_dataset.csv")
df

                                       message_content  is_spam
0    Hello Lonnie,\n\nJust wanted to touch base reg...        0
1    Congratulations, you've won a prize! Call us n...        1
2    You have been pre-approved for a credit card w...        1
3    Limited time offer, act now! Only a few spots ...        1
4    Your loan has been approved! Transfer funds to...        1
..                                                 ...      ...
995  Hello Virginia,\n\nIt was great to catch up wi...        0
996  Final notice: Claim your inheritance from a di...        1
997  Hot singles in your area want to chat! Contact...        1
998  Your loan has been approved! Transfer funds to...        1
999  Dear Brian,\n\nI wanted to let you know about ...        0

[1000 rows x 2 columns]

In [106]:
X = df['message_content']
y = df['is_spam']

# Extra steps here: Convert text to numbers
cv = CountVectorizer()
X_cv = cv.fit_transform(X)

model = LogisticRegression()
model.fit(X_cv, y)

LogisticRegression()

In [109]:
# Step 8: Try custom messages
sample =  ["Just wanted to touch base"]   # Enter email here
pred = model.predict(cv.transform(sample))
if(pred[0]):
    print('Not Spam')
else:
    print('SPAM')

Not Spam