In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn. metrics.pairwise import cosine_similarity

In [56]:
df = pd.read_csv('/content/sample_data/UpdatedResumeDataSet.csv',encoding='utf-8')
print('Shape of Data Frame',df.shape)
df.head()

Shape of Data Frame (962, 2)

       Category                                             Resume
0  Data Science  Skills * Programming Languages: Python (pandas...
1  Data Science  Education Details \r\nMay 2013 to May 2017 B.E...
2  Data Science  Areas of Interest Deep Learning, Control Syste...
3  Data Science  Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...
4  Data Science  Education Details \r\n MCA   YMCAUST,  Faridab...

In [57]:
print('\n Columns',df.columns.tolist())

 Columns ['Category', 'Resume']

In [58]:
sample_df=df.sample(10,random_state=42).reset_index(drop=True)
sample_df

,Category,Resume
0,Java Developer,TECHNICAL SKILLS Programming Languages: Java (...
1,Java Developer,"TECHNICALSKILLS SpringMVC, Hibernate, JDBC, Ja..."
2,Java Developer,Education Details \r\nJanuary 2013 Master of E...
3,Hadoop,"Skill Set: Hadoop, Map Reduce, HDFS, Hive, Sqo..."
4,Health and fitness,Education Details \r\nJanuary 1992 to January ...
5,Network Security Engineer,"Technical Expertise: â¢ Cisco ASA, Checkpoint..."
6,Mechanical Engineer,Education Details \r\nMay 1999 to September 20...
7,Automation Testing,"Technical Skills Summary I have completed ""COR..."
8,Advocate,Education Details \r\n LLB. Dibrugarh Univer...
9,Health and fitness,SKILLS: Computer: â¢ Can easily operate in Op...

In [59]:
sample_df = sample_df.rename(columns={'Resume':'Resume_Text'})
sample_df

,Category,Resume_Text
0,Java Developer,TECHNICAL SKILLS Programming Languages: Java (...
1,Java Developer,"TECHNICALSKILLS SpringMVC, Hibernate, JDBC, Ja..."
2,Java Developer,Education Details \r\nJanuary 2013 Master of E...
3,Hadoop,"Skill Set: Hadoop, Map Reduce, HDFS, Hive, Sqo..."
4,Health and fitness,Education Details \r\nJanuary 1992 to January ...
5,Network Security Engineer,"Technical Expertise: â¢ Cisco ASA, Checkpoint..."
6,Mechanical Engineer,Education Details \r\nMay 1999 to September 20...
7,Automation Testing,"Technical Skills Summary I have completed ""COR..."
8,Advocate,Education Details \r\n LLB. Dibrugarh Univer...
9,Health and fitness,SKILLS: Computer: â¢ Can easily operate in Op...

In [60]:
# Step 1: Initialize the TF-IDF vectorizer
# stop_words='english' removes common English words like 'the', 'is', 'and'
vectorizer = TfidfVectorizer(stop_words='english')

# Step 2: Fit the vectorizer on the 'Resume_Text' column
# and transform the text into a TF-IDF matrix
# Each resume will be converted into a vector of TF-IDF features
tfidf_matrix = vectorizer.fit_transform(sample_df['Resume_Text'])

# Step 3: Check the shape of the TF-IDF matrix
# The output is (number_of_documents, number_of_features)
tfidf_matrix.shape

(10, 1125)

In [61]:
# Compute cosine similarity
similarity_matrix = cosine_similarity(tfidf_matrix)

# Convert to DataFrame with proper index and columns
sim_df = pd.DataFrame(
    similarity_matrix,
    index=sample_df["Category"] + "_" + sample_df.index.astype(str),
    columns=sample_df["Category"] + "_" + sample_df.index.astype(str)
)

sim_df.round(2).head()

,Java Developer_0,Java Developer_1,Java Developer_2,Hadoop_3,Health and fitness_4,Network Security Engineer_5,Mechanical Engineer_6,Automation Testing_7,Advocate_8,Health and fitness_9
Java Developer_0,1.00,0.41,0.24,0.11,0.06,0.07,0.06,0.10,0.11,0.08
Java Developer_1,0.41,1.00,0.22,0.14,0.03,0.05,0.03,0.09,0.09,0.06
Java Developer_2,0.24,0.22,1.00,0.11,0.07,0.07,0.07,0.08,0.05,0.03
Hadoop_3,0.11,0.14,0.11,1.00,0.02,0.04,0.05,0.06,0.05,0.04
Health and fitness_4,0.06,0.03,0.07,0.02,1.00,0.03,0.04,0.08,0.09,0.35

## Resume Screening Example 2

In [62]:
resumes={
    "candidate":['Sam','Arsh','Maan'],
    "resume_text":["Python developer skilled in Django,Flask, Rest API and MySQL",
                   "Machine learning engineer experience in Python,TensorFlow, NLP and data analysis",
                   "Full stack developer with .net, javascript,React, Node.js and MongoDB experience" ]
}

In [63]:
df=pd.DataFrame(resumes)
df

  candidate                                        resume_text
0       Sam  Python developer skilled in Django,Flask, Rest...
1      Arsh  Machine learning engineer experience in Python...
2      Maan  Full stack developer with .net, javascript,Rea...

In [64]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Step 1: Initialize TF-IDF Vectorizer
# stop_words='english' ignores common English words
vectorizer = TfidfVectorizer(stop_words='english')

# Step 2: Fit the vectorizer and transform the 'resume_text' column
# Each document (resume) is converted into a TF-IDF vector
tfidf_matrix = vectorizer.fit_transform(df['resume_text'])

# Step 3: Check the shape of the TF-IDF matrix
# Output: (number_of_documents, number_of_features)
print(tfidf_matrix.shape)

# Step 4: View the TF-IDF matrix
tfidf_matrix

(3, 23)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 26 stored elements and shape (3, 23)>

In [65]:
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

# Step 1: Compute cosine similarity between all resumes
similarity_matrix = cosine_similarity(tfidf_matrix)

# Step 2: Convert the similarity matrix into a pandas DataFrame
# Use 'candidate' column for row and column labels
sim_df = pd.DataFrame(
    similarity_matrix,
    index=df["candidate"],
    columns=df["candidate"]
)

# Step 3: Round the values to 2 decimal places for readability
sim_df = sim_df.round(2)

# Display the similarity DataFrame
sim_df

candidate   Sam  Arsh  Maan
candidate
Sam        1.00  0.08  0.08
Arsh       0.08  1.00  0.07
Maan       0.08  0.07  1.00

In [66]:
# Add a new row to the DataFrame
df.loc[len(df)] = ["Zoya", "Backend developer skilled in Python, Flask and SQL"]

# Display updated DataFrame
df

  candidate                                        resume_text
0       Sam  Python developer skilled in Django,Flask, Rest...
1      Arsh  Machine learning engineer experience in Python...
2      Maan  Full stack developer with .net, javascript,Rea...
3      Zoya  Backend developer skilled in Python, Flask and...

In [67]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Step 1: Initialize the TF-IDF vectorizer
# stop_words='english' ignores common English words like 'the', 'is', 'and'
vectorizer = TfidfVectorizer(stop_words='english')

# Step 2: Fit the vectorizer on the 'resume_text' column
# and transform the text into a TF-IDF matrix
tfidf_matrix = vectorizer.fit_transform(df['resume_text'])

# Step 3: Check the shape of the TF-IDF matrix
# Output: (number_of_documents, number_of_features)
print(tfidf_matrix.shape)

# Step 4: View the TF-IDF matrix
tfidf_matrix

(4, 25)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 32 stored elements and shape (4, 25)>

In [68]:
similarity_matrix = cosine_similarity(tfidf_matrix)
sim_df = pd.DataFrame(
    similarity_matrix,
    index=df["candidate"],
    columns=df["candidate"]
)
sim_df = sim_df.round(2)
sim_df

candidate   Sam  Arsh  Maan  Zoya
candidate
Sam        1.00  0.06  0.06  0.42
Arsh       0.06  1.00  0.08  0.07
Maan       0.06  0.08  1.00  0.07
Zoya       0.42  0.07  0.07  1.00