## Basic panda example to read out from an excel file

In [20]:
import pandas as pd

In [21]:
df=pd.read_excel('students.xlsx')

In [22]:
print('Print data frame as follows')
df

Print data frame as follows

    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45

In [32]:
dfpatients=pd.read_csv("E:/AIML/aimltraining/Day-10/patients.csv")

In [33]:
dfpatients

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,ICU,76
...,...,...,...,...,...,...,...
995,PAT-a01bf534,Amber Vang,26,2025-12-02,2025-12-04,emergency,91
996,PAT-87fa07bd,Martha Smith,89,2025-11-18,2025-11-30,emergency,99
997,PAT-8f07e894,Jennifer James,72,2025-12-12,2025-12-21,ICU,69
998,PAT-4ae301e1,Kara Hernandez,47,2025-02-08,2025-02-20,ICU,61
999,PAT-e2ef9c5f,Lorraine Turner,64,2025-05-04,2025-05-08,general_medicine,83

In [34]:
dfpatients['name']

0      Richard Rodriguez
1         Shannon Walker
2           Julia Torres
3        Crystal Johnson
4            Garrett Lin
             ...
995           Amber Vang
996         Martha Smith
997       Jennifer James
998       Kara Hernandez
999      Lorraine Turner
Name: name, Length: 1000, dtype: object

In [35]:
print(dfpatients['name'])

0      Richard Rodriguez
1         Shannon Walker
2           Julia Torres
3        Crystal Johnson
4            Garrett Lin
             ...
995           Amber Vang
996         Martha Smith
997       Jennifer James
998       Kara Hernandez
999      Lorraine Turner
Name: name, Length: 1000, dtype: object

# head in dataframe

In [36]:
df.head()

    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90

In [37]:
dfpatients.head()

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,ICU,76

In [38]:
dfpatients.head(2)

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83

# tail example

In [39]:
print('Last Two students in Excel Sheet')
df.tail(2)

Last Two students in Excel Sheet

    Name  Age  Marks
4    Sam   25     90
5  Rohit   23     45

In [40]:
dfpatients.tail()

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
995,PAT-a01bf534,Amber Vang,26,2025-12-02,2025-12-04,emergency,91
996,PAT-87fa07bd,Martha Smith,89,2025-11-18,2025-11-30,emergency,99
997,PAT-8f07e894,Jennifer James,72,2025-12-12,2025-12-21,ICU,69
998,PAT-4ae301e1,Kara Hernandez,47,2025-02-08,2025-02-20,ICU,61
999,PAT-e2ef9c5f,Lorraine Turner,64,2025-05-04,2025-05-08,general_medicine,83

In [41]:
dfpatients.tail(10)

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
990,PAT-110d5794,Travis Hull,48,2025-11-12,2025-11-18,ICU,89
991,PAT-c7aac776,Darryl Acosta,83,2025-10-11,2025-10-20,surgery,91
992,PAT-8700b93a,Nicholas Lawrence,9,2025-10-25,2025-11-02,ICU,92
993,PAT-e5d6a9cf,Jacob Santos,76,2025-12-27,2026-01-02,ICU,96
994,PAT-2fa08c0d,Shawn Scott,79,2025-01-22,2025-01-31,emergency,79
995,PAT-a01bf534,Amber Vang,26,2025-12-02,2025-12-04,emergency,91
996,PAT-87fa07bd,Martha Smith,89,2025-11-18,2025-11-30,emergency,99
997,PAT-8f07e894,Jennifer James,72,2025-12-12,2025-12-21,ICU,69
998,PAT-4ae301e1,Kara Hernandez,47,2025-02-08,2025-02-20,ICU,61
999,PAT-e2ef9c5f,Lorraine Turner,64,2025-05-04,2025-05-08,general_medicine,83

# shape example shape returns you (rows,columns)

In [42]:
dfpatients.shape

(1000, 7)

In [43]:
df.shape

(6, 3)

In [44]:
df.shape

(6, 3)

In [45]:
r,c=dfpatients.shape
print(f"Rows: {r} Columns: {c} ")

Rows: 1000 Columns: 7

In [46]:
r,c=df.shape
print('Rows and Columns in Students Sheet')
print(f"Rows: {r} Columns: {c} ")

Rows and Columns in Students Sheet
Rows: 6 Columns: 3

# values: in dataframe
    Excel and CSV files

In [47]:
print('Student Values')
df.values

Student Values

array([['John', 20, 85],
       ['Alice', 22, 90],
       ['Bob', 21, 78],
       ['Sara', 23, 92],
       ['Sam', 25, 90],
       ['Rohit', 23, 45]], dtype=object)

In [48]:
print('Patients Values')
dfpatients.values

Patients Values

array([['PAT-09484753', 'Richard Rodriguez', 24, ..., '2025-03-22',
        'surgery', 61],
       ['PAT-f0644084', 'Shannon Walker', 6, ..., '2025-12-14',
        'surgery', 83],
       ['PAT-ac6162e4', 'Julia Torres', 24, ..., '2025-07-05',
        'general_medicine', 83],
       ...,
       ['PAT-8f07e894', 'Jennifer James', 72, ..., '2025-12-21', 'ICU',
        69],
       ['PAT-4ae301e1', 'Kara Hernandez', 47, ..., '2025-02-20', 'ICU',
        61],
       ['PAT-e2ef9c5f', 'Lorraine Turner', 64, ..., '2025-05-08',
        'general_medicine', 83]], dtype=object)