In [134]:
import tensorflow as tf
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [135]:
data = {
    "overview":
    [
        "A hero saves the city from destruction",
        "A girl and boy become friends during war",
        "A funny story of colleagues during office meet",
        "One scary night in a deserted level"
    ],
    "genres":[["Action","Adventure",],["Romance","Drama"],["Comedy"],["Horror"]]
}

In [136]:
df=pd.DataFrame(data)
df

                                         overview               genres
0          A hero saves the city from destruction  [Action, Adventure]
1        A girl and boy become friends during war     [Romance, Drama]
2  A funny story of colleagues during office meet             [Comedy]
3             One scary night in a deserted level             [Horror]

In [137]:
mlb = MultiLabelBinarizer()
y = mlb.fit_transform(df["genres"])

In [138]:
y

array([[1, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0]])

In [139]:
tokenizer = Tokenizer(num_words=5000,oov_token="<OOV>")
tokenizer.fit_on_texts(df["overview"])
X = tokenizer.texts_to_sequences(df["overview"])
X = pad_sequences(X,maxlen=20,padding='post')

In [140]:
print(mlb.classes_)

['Action' 'Adventure' 'Comedy' 'Drama' 'Horror' 'Romance']

In [141]:
model=tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=5000,output_dim=16,input_length=20),
    tf.keras.layers.GlobalAveragePooling1D(),
    tf.keras.layers.Dense(16,activation="relu"),
    tf.keras.layers.Dense(len(mlb.classes_), activation="sigmoid")
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [142]:
model.compile(optimizer='adam' , loss='binary_crossentropy' , metrics=['accuracy' ])

In [143]:
print(X.shape)
print(y.shape)

(4, 20)
(4, 6)

In [144]:
history = model.fit(X,y,epochs=20,verbose=2)

Epoch 1/20
1/1 - 1s - 1s/step - accuracy: 0.2500 - loss: 0.6973
Epoch 2/20
1/1 - 0s - 46ms/step - accuracy: 0.2500 - loss: 0.6956
Epoch 3/20
1/1 - 0s - 45ms/step - accuracy: 0.2500 - loss: 0.6940
Epoch 4/20
1/1 - 0s - 46ms/step - accuracy: 0.5000 - loss: 0.6925
Epoch 5/20
1/1 - 0s - 47ms/step - accuracy: 0.2500 - loss: 0.6912
Epoch 6/20
1/1 - 0s - 46ms/step - accuracy: 0.0000e+00 - loss: 0.6900
Epoch 7/20
1/1 - 0s - 57ms/step - accuracy: 0.0000e+00 - loss: 0.6890
Epoch 8/20
1/1 - 0s - 47ms/step - accuracy: 0.0000e+00 - loss: 0.6882
Epoch 9/20
1/1 - 0s - 49ms/step - accuracy: 0.0000e+00 - loss: 0.6874
Epoch 10/20
1/1 - 0s - 45ms/step - accuracy: 0.0000e+00 - loss: 0.6868
Epoch 11/20
1/1 - 0s - 52ms/step - accuracy: 0.0000e+00 - loss: 0.6861
Epoch 12/20
1/1 - 0s - 47ms/step - accuracy: 0.0000e+00 - loss: 0.6854
Epoch 13/20
1/1 - 0s - 46ms/step - accuracy: 0.0000e+00 - loss: 0.6846
Epoch 14/20
1/1 - 0s - 44ms/step - accuracy: 0.0000e+00 - loss: 0.6838
Epoch 15/20
1/1 - 0s - 46ms/step - accuracy: 0.0000e+00 - loss: 0.6828
Epoch 16/20
1/1 - 0s - 46ms/step - accuracy: 0.0000e+00 - loss: 0.6819
Epoch 17/20
1/1 - 0s - 51ms/step - accuracy: 0.0000e+00 - loss: 0.6809
Epoch 18/20
1/1 - 0s - 49ms/step - accuracy: 0.0000e+00 - loss: 0.6798
Epoch 19/20
1/1 - 0s - 48ms/step - accuracy: 0.0000e+00 - loss: 0.6787
Epoch 20/20
1/1 - 0s - 136ms/step - accuracy: 0.0000e+00 - loss: 0.6776

In [145]:
# Predict on a new movie overview
new_movie_overview = ['karate kid' ]
seq=tokenizer. texts_to_sequences(new_movie_overview)
seq=pad_sequences(seq,maxlen=20, padding='post' )
prediction=model.predict(seq)
prediction_labels=[mlb.classes_[i] for i in range(len(prediction[0])) if prediction[0][i]>0.5]
print('Predicted Genres: ', prediction_labels)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step
Predicted Genres:  ['Adventure']

### Exercise
- Use the dataset to write one more MultiLabel Classification prediction using neural network

In [146]:
data = {
    "headline": [
        "Government launches new digital economy policy",
        "Star player wins championship after dramatic final",
        "Tech company releases AI-powered smartphone",
        "Stock market drops amid political tensions",
        "New environmental policy gains global support",
        "Space agency announces manned Mars mission"
    ],
    "topics": [
        ["Politics", "Economy", "Technology"],
        ["Sports"],
        ["Technology", "Business"],
        ["Economy", "Politics"],
        ["Environment", "Politics"],
        ["Science", "Technology"]
    ]
}

In [147]:
df=pd.DataFrame(data)
df

,headline,topics
0,Government launches new digital economy policy,"[Politics, Economy, Technology]"
1,Star player wins championship after dramatic f...,[Sports]
2,Tech company releases AI-powered smartphone,"[Technology, Business]"
3,Stock market drops amid political tensions,"[Economy, Politics]"
4,New environmental policy gains global support,"[Environment, Politics]"
5,Space agency announces manned Mars mission,"[Science, Technology]"

In [148]:
mlb = MultiLabelBinarizer()
y = mlb.fit_transform(df["topics"])

In [149]:
tokenizer = Tokenizer(num_words=5000,oov_token="<OOV>")
tokenizer.fit_on_texts(df["headline"])
X = tokenizer.texts_to_sequences(df["headline"])
X = pad_sequences(X,maxlen=20,padding='post')

In [150]:
model=tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=5000,output_dim=16,input_length=20),
    tf.keras.layers.GlobalAveragePooling1D(),
    tf.keras.layers.Dense(16,activation="relu"),
    tf.keras.layers.Dense(len(mlb.classes_), activation="sigmoid")
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [151]:
model.compile(optimizer='adam' , loss='binary_crossentropy' , metrics=['accuracy' ])

In [152]:
history = model.fit(X,y,epochs=20,verbose=2)

Epoch 1/20
1/1 - 2s - 2s/step - accuracy: 0.3333 - loss: 0.6920
Epoch 2/20
1/1 - 0s - 137ms/step - accuracy: 0.3333 - loss: 0.6909
Epoch 3/20
1/1 - 0s - 67ms/step - accuracy: 0.3333 - loss: 0.6899
Epoch 4/20
1/1 - 0s - 67ms/step - accuracy: 0.3333 - loss: 0.6888
Epoch 5/20
1/1 - 0s - 72ms/step - accuracy: 0.3333 - loss: 0.6878
Epoch 6/20
1/1 - 0s - 67ms/step - accuracy: 0.3333 - loss: 0.6868
Epoch 7/20
1/1 - 0s - 141ms/step - accuracy: 0.3333 - loss: 0.6858
Epoch 8/20
1/1 - 0s - 143ms/step - accuracy: 0.3333 - loss: 0.6847
Epoch 9/20
1/1 - 0s - 75ms/step - accuracy: 0.3333 - loss: 0.6837
Epoch 10/20
1/1 - 0s - 139ms/step - accuracy: 0.3333 - loss: 0.6826
Epoch 11/20
1/1 - 0s - 76ms/step - accuracy: 0.3333 - loss: 0.6815
Epoch 12/20
1/1 - 0s - 140ms/step - accuracy: 0.3333 - loss: 0.6803
Epoch 13/20
1/1 - 0s - 72ms/step - accuracy: 0.3333 - loss: 0.6791
Epoch 14/20
1/1 - 0s - 77ms/step - accuracy: 0.3333 - loss: 0.6778
Epoch 15/20
1/1 - 0s - 126ms/step - accuracy: 0.3333 - loss: 0.6763
Epoch 16/20
1/1 - 0s - 49ms/step - accuracy: 0.3333 - loss: 0.6749
Epoch 17/20
1/1 - 0s - 55ms/step - accuracy: 0.3333 - loss: 0.6734
Epoch 18/20
1/1 - 0s - 46ms/step - accuracy: 0.0000e+00 - loss: 0.6718
Epoch 19/20
1/1 - 0s - 47ms/step - accuracy: 0.0000e+00 - loss: 0.6702
Epoch 20/20
1/1 - 0s - 45ms/step - accuracy: 0.0000e+00 - loss: 0.6686

In [156]:
# Predict topic based on headline
new_topic_overview = ['what do you think' ]
seq=tokenizer. texts_to_sequences(new_topic_overview)
seq=pad_sequences(seq,maxlen=20, padding='post' )
prediction=model.predict(seq)
prediction_labels=[mlb.classes_[i] for i in range(len(prediction[0])) if prediction[0][i]>0.5]
print('Predicted Topic: ', prediction_labels)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
Predicted Topic:  ['Economy', 'Politics', 'Technology']