Steps For Modeling:

- Creating the Model
- Compiling th Model
- Define a loss function
- Setting up an optimizer
- Finding best learning size
- Creating Evalution Metrics
- Fitting Model
- Imporve Model

Predict Heart Disease

1. Load DataSet
2. Spilt features and Test
3. Train Trest Spil 4 . Scale Features

In [53]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

In [54]:
heart_data = pd.read_csv("/content/sample_data/heart.csv")
heart_data.head()

   age  sex  chol  trestbps  thalach  target
0   52    1   200       130      150       1
1   58    0   240       150      140       1
2   60    1   180       140      145       0
3   48    1   190       120      160       0
4   50    0   220       125      155       1

In [55]:
X = heart_data.drop("target", axis=1)
y = heart_data["target"]

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [57]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [58]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation="relu", input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(32, activation="relu"),
    tf.keras.layers.Dense(1, activation="sigmoid")
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [59]:
# Compile model
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [60]:
# Train model
history = model.fit(X_train_scaled, y_train, epochs=100, batch_size=32, validation_split=0.2)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.5000 - loss: 0.6516 - val_accuracy: 0.5000 - val_loss: 0.7434
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 338ms/step - accuracy: 0.5000 - loss: 0.6412 - val_accuracy: 0.5000 - val_loss: 0.7440
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 218ms/step - accuracy: 0.6667 - loss: 0.6310 - val_accuracy: 0.5000 - val_loss: 0.7437
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 273ms/step - accuracy: 0.8333 - loss: 0.6214 - val_accuracy: 0.5000 - val_loss: 0.7439
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 374ms/step - accuracy: 0.8333 - loss: 0.6121 - val_accuracy: 0.5000 - val_loss: 0.7443
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 308ms/step - accuracy: 0.8333 - loss: 0.6027 - val_accuracy: 0.5000 - val_loss: 0.7452
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 348ms/step - accuracy: 0.8333 - loss: 0.5932 - val_accuracy: 0.5000 - val_loss: 0.7460
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 356ms/step - accuracy: 0.8333 - loss: 0.5839 - val_accuracy: 0.5000 - val_loss: 0.7469
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 329ms/step - accuracy: 0.8333 - loss: 0.5749 - val_accuracy: 0.5000 - val_loss: 0.7481
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 350ms/step - accuracy: 0.8333 - loss: 0.5659 - val_accuracy: 0.5000 - val_loss: 0.7495
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 578ms/step - accuracy: 0.8333 - loss: 0.5571 - val_accuracy: 0.5000 - val_loss: 0.7516
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - accuracy: 0.8333 - loss: 0.5487 - val_accuracy: 0.5000 - val_loss: 0.7537
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.8333 - loss: 0.5404 - val_accuracy: 0.5000 - val_loss: 0.7560
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 0.8333 - loss: 0.5323 - val_accuracy: 0.5000 - val_loss: 0.7580
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.8333 - loss: 0.5242 - val_accuracy: 0.5000 - val_loss: 0.7601
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.8333 - loss: 0.5163 - val_accuracy: 0.5000 - val_loss: 0.7621
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.8333 - loss: 0.5085 - val_accuracy: 0.5000 - val_loss: 0.7634
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.8333 - loss: 0.5006 - val_accuracy: 0.5000 - val_loss: 0.7648
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.4928 - val_accuracy: 0.5000 - val_loss: 0.7662
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.4849 - val_accuracy: 0.5000 - val_loss: 0.7679
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.4771 - val_accuracy: 0.5000 - val_loss: 0.7695
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 1.0000 - loss: 0.4694 - val_accuracy: 0.5000 - val_loss: 0.7710
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 1.0000 - loss: 0.4620 - val_accuracy: 0.5000 - val_loss: 0.7727
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - accuracy: 1.0000 - loss: 0.4548 - val_accuracy: 0.5000 - val_loss: 0.7749
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 1.0000 - loss: 0.4475 - val_accuracy: 0.5000 - val_loss: 0.7772
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 1.0000 - loss: 0.4401 - val_accuracy: 0.5000 - val_loss: 0.7801
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 1.0000 - loss: 0.4328 - val_accuracy: 0.5000 - val_loss: 0.7834
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - accuracy: 1.0000 - loss: 0.4254 - val_accuracy: 0.5000 - val_loss: 0.7868
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 1.0000 - loss: 0.4181 - val_accuracy: 0.5000 - val_loss: 0.7900
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 1.0000 - loss: 0.4109 - val_accuracy: 0.5000 - val_loss: 0.7933
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 1.0000 - loss: 0.4037 - val_accuracy: 0.5000 - val_loss: 0.7964
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 1.0000 - loss: 0.3964 - val_accuracy: 0.5000 - val_loss: 0.7993
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - accuracy: 1.0000 - loss: 0.3891 - val_accuracy: 0.5000 - val_loss: 0.8020
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - accuracy: 1.0000 - loss: 0.3818 - val_accuracy: 0.5000 - val_loss: 0.8050
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 1.0000 - loss: 0.3746 - val_accuracy: 0.5000 - val_loss: 0.8085
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 1.0000 - loss: 0.3674 - val_accuracy: 0.5000 - val_loss: 0.8123
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 1.0000 - loss: 0.3603 - val_accuracy: 0.5000 - val_loss: 0.8155
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 1.0000 - loss: 0.3533 - val_accuracy: 0.5000 - val_loss: 0.8187
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 1.0000 - loss: 0.3463 - val_accuracy: 0.5000 - val_loss: 0.8218
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 1.0000 - loss: 0.3393 - val_accuracy: 0.5000 - val_loss: 0.8249
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 1.0000 - loss: 0.3323 - val_accuracy: 0.5000 - val_loss: 0.8279
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - accuracy: 1.0000 - loss: 0.3255 - val_accuracy: 0.5000 - val_loss: 0.8310
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - accuracy: 1.0000 - loss: 0.3186 - val_accuracy: 0.5000 - val_loss: 0.8343
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 1.0000 - loss: 0.3118 - val_accuracy: 0.5000 - val_loss: 0.8375
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - accuracy: 1.0000 - loss: 0.3054 - val_accuracy: 0.5000 - val_loss: 0.8410
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 1.0000 - loss: 0.2988 - val_accuracy: 0.5000 - val_loss: 0.8452
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 1.0000 - loss: 0.2923 - val_accuracy: 0.5000 - val_loss: 0.8498
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - accuracy: 1.0000 - loss: 0.2857 - val_accuracy: 0.5000 - val_loss: 0.8548
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.2792 - val_accuracy: 0.5000 - val_loss: 0.8596
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.2729 - val_accuracy: 0.5000 - val_loss: 0.8645
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - accuracy: 1.0000 - loss: 0.2668 - val_accuracy: 0.5000 - val_loss: 0.8690
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.2607 - val_accuracy: 0.5000 - val_loss: 0.8733
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.2545 - val_accuracy: 0.5000 - val_loss: 0.8776
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.2485 - val_accuracy: 0.5000 - val_loss: 0.8817
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - accuracy: 1.0000 - loss: 0.2425 - val_accuracy: 0.5000 - val_loss: 0.8864
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.2366 - val_accuracy: 0.5000 - val_loss: 0.8916
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 1.0000 - loss: 0.2308 - val_accuracy: 0.5000 - val_loss: 0.8972
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.2250 - val_accuracy: 0.5000 - val_loss: 0.9023
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 1.0000 - loss: 0.2193 - val_accuracy: 0.5000 - val_loss: 0.9065
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 1.0000 - loss: 0.2139 - val_accuracy: 0.5000 - val_loss: 0.9103
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 1.0000 - loss: 0.2085 - val_accuracy: 0.5000 - val_loss: 0.9138
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.2031 - val_accuracy: 0.5000 - val_loss: 0.9175
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.1977 - val_accuracy: 0.5000 - val_loss: 0.9221
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 1.0000 - loss: 0.1924 - val_accuracy: 0.5000 - val_loss: 0.9267
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 1.0000 - loss: 0.1872 - val_accuracy: 0.5000 - val_loss: 0.9319
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 1.0000 - loss: 0.1822 - val_accuracy: 0.5000 - val_loss: 0.9368
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 1.0000 - loss: 0.1773 - val_accuracy: 0.5000 - val_loss: 0.9416
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 1.0000 - loss: 0.1725 - val_accuracy: 0.5000 - val_loss: 0.9463
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 1.0000 - loss: 0.1678 - val_accuracy: 0.5000 - val_loss: 0.9516
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 1.0000 - loss: 0.1631 - val_accuracy: 0.5000 - val_loss: 0.9576
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.1585 - val_accuracy: 0.5000 - val_loss: 0.9638
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 1.0000 - loss: 0.1541 - val_accuracy: 0.5000 - val_loss: 0.9697
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 1.0000 - loss: 0.1498 - val_accuracy: 0.5000 - val_loss: 0.9753
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 1.0000 - loss: 0.1455 - val_accuracy: 0.5000 - val_loss: 0.9810
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 1.0000 - loss: 0.1413 - val_accuracy: 0.5000 - val_loss: 0.9865
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.1373 - val_accuracy: 0.5000 - val_loss: 0.9915
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 1.0000 - loss: 0.1334 - val_accuracy: 0.5000 - val_loss: 0.9961
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 1.0000 - loss: 0.1295 - val_accuracy: 0.5000 - val_loss: 1.0003
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.1257 - val_accuracy: 0.5000 - val_loss: 1.0048
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 1.0000 - loss: 0.1221 - val_accuracy: 0.5000 - val_loss: 1.0094
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 1.0000 - loss: 0.1185 - val_accuracy: 0.5000 - val_loss: 1.0140
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.1150 - val_accuracy: 0.5000 - val_loss: 1.0181
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - accuracy: 1.0000 - loss: 0.1116 - val_accuracy: 0.5000 - val_loss: 1.0216
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.1083 - val_accuracy: 0.5000 - val_loss: 1.0249
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 1.0000 - loss: 0.1051 - val_accuracy: 0.5000 - val_loss: 1.0286
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.1020 - val_accuracy: 0.5000 - val_loss: 1.0333
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 1.0000 - loss: 0.0990 - val_accuracy: 0.5000 - val_loss: 1.0389
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 1.0000 - loss: 0.0960 - val_accuracy: 0.5000 - val_loss: 1.0447
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 1.0000 - loss: 0.0932 - val_accuracy: 0.5000 - val_loss: 1.0502
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - accuracy: 1.0000 - loss: 0.0905 - val_accuracy: 0.5000 - val_loss: 1.0549
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - accuracy: 1.0000 - loss: 0.0878 - val_accuracy: 0.5000 - val_loss: 1.0596
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 1.0000 - loss: 0.0852 - val_accuracy: 0.5000 - val_loss: 1.0649
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - accuracy: 1.0000 - loss: 0.0827 - val_accuracy: 0.5000 - val_loss: 1.0707
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 1.0000 - loss: 0.0803 - val_accuracy: 0.5000 - val_loss: 1.0768
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 1.0000 - loss: 0.0779 - val_accuracy: 0.5000 - val_loss: 1.0831
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 1.0000 - loss: 0.0756 - val_accuracy: 0.5000 - val_loss: 1.0894
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.0734 - val_accuracy: 0.5000 - val_loss: 1.0951
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.0712 - val_accuracy: 0.5000 - val_loss: 1.1010
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 1.0000 - loss: 0.0692 - val_accuracy: 0.5000 - val_loss: 1.1070
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 1.0000 - loss: 0.0672 - val_accuracy: 0.5000 - val_loss: 1.1125

In [61]:
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 263ms/step - accuracy: 0.5000 - loss: 35.1519
Test Loss: 35.151893615722656
Test Accuracy: 0.5

# Example 2
*Bank Customer Exit Prediction.
* Based on given data using Neural Network Binary Classifier find out
is a customer going to stay or leave
stay: (Churn=0) and leave (churn=1)
*Bredict the result for new data as well at end

In [62]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import tensorflow as tf
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [63]:
bank_data = pd.read_csv("/content/sample_data/bank_churn.csv")
bank_data.head()

,CreditScore,Geography,Gender,Age,Balance,NumOfProducts,EstimatedSalary,Exited
0,600,France,Male,40,60000,1,50000,0
1,700,Spain,Female,45,70000,2,60000,0
2,800,Germany,Female,38,80000,1,70000,1
3,400,France,Male,30,30000,1,40000,1
4,550,Spain,Male,50,40000,2,42000,0

In [64]:
le=LabelEncoder()
bank_data['Gender']=le.fit_transform(bank_data['Gender' ])
bank_data=pd.get_dummies(bank_data, columns=['Geography' ])

X=bank_data.drop(['Exited'],axis=1)
y=bank_data['Exited' ]

In [65]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [66]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [67]:
bank_model = tf.keras.Sequential([
    tf.keras.layers.Dense(16, activation="relu", input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(8, activation="relu"),
    tf.keras.layers.Dense(1, activation="sigmoid")
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [68]:
bank_model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
bank_model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_20 (Dense)                │ (None, 16)             │           160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_22 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 305 (1.19 KB)

 Trainable params: 305 (1.19 KB)

 Non-trainable params: 0 (0.00 B)

In [69]:
bank_model_history=bank_model.fit(X_train_scaled,y_train, epochs=100, validation_data=(X_test_scaled, y_test))

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.5000 - loss: 0.8064 - val_accuracy: 0.5000 - val_loss: 0.6989
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 320ms/step - accuracy: 0.5000 - loss: 0.7991 - val_accuracy: 0.5000 - val_loss: 0.6988
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 0.5000 - loss: 0.7920 - val_accuracy: 0.5000 - val_loss: 0.6988
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step - accuracy: 0.5000 - loss: 0.7849 - val_accuracy: 0.5000 - val_loss: 0.6989
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step - accuracy: 0.5000 - loss: 0.7781 - val_accuracy: 0.5000 - val_loss: 0.6989
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.5000 - loss: 0.7721 - val_accuracy: 0.5000 - val_loss: 0.6990
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.5000 - loss: 0.7661 - val_accuracy: 0.5000 - val_loss: 0.6990
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.5000 - loss: 0.7601 - val_accuracy: 0.5000 - val_loss: 0.6992
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.5000 - loss: 0.7542 - val_accuracy: 0.5000 - val_loss: 0.6993
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.5000 - loss: 0.7484 - val_accuracy: 0.5000 - val_loss: 0.6994
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.5000 - loss: 0.7426 - val_accuracy: 0.5000 - val_loss: 0.6996
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.5000 - loss: 0.7369 - val_accuracy: 0.5000 - val_loss: 0.6999
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.5000 - loss: 0.7313 - val_accuracy: 0.5000 - val_loss: 0.7001
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.5000 - loss: 0.7257 - val_accuracy: 0.5000 - val_loss: 0.7003
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - accuracy: 0.5000 - loss: 0.7201 - val_accuracy: 0.5000 - val_loss: 0.7006
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 0.5000 - loss: 0.7147 - val_accuracy: 0.5000 - val_loss: 0.7009
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.5000 - loss: 0.7093 - val_accuracy: 0.5000 - val_loss: 0.7012
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - accuracy: 0.5000 - loss: 0.7039 - val_accuracy: 0.5000 - val_loss: 0.7015
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - accuracy: 0.5000 - loss: 0.6986 - val_accuracy: 0.5000 - val_loss: 0.7019
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 0.5000 - loss: 0.6934 - val_accuracy: 0.5000 - val_loss: 0.7022
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 0.5000 - loss: 0.6882 - val_accuracy: 0.5000 - val_loss: 0.7026
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.5000 - loss: 0.6830 - val_accuracy: 0.5000 - val_loss: 0.7040
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - accuracy: 0.5000 - loss: 0.6779 - val_accuracy: 0.5000 - val_loss: 0.7054
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.5000 - loss: 0.6729 - val_accuracy: 0.5000 - val_loss: 0.7068
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 0.5000 - loss: 0.6679 - val_accuracy: 0.5000 - val_loss: 0.7080
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 0.5000 - loss: 0.6629 - val_accuracy: 0.5000 - val_loss: 0.7093
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.5000 - loss: 0.6580 - val_accuracy: 0.5000 - val_loss: 0.7106
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 0.5000 - loss: 0.6531 - val_accuracy: 0.5000 - val_loss: 0.7120
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.5000 - loss: 0.6484 - val_accuracy: 0.5000 - val_loss: 0.7135
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.5000 - loss: 0.6436 - val_accuracy: 0.5000 - val_loss: 0.7150
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.5000 - loss: 0.6388 - val_accuracy: 0.5000 - val_loss: 0.7168
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - accuracy: 0.5000 - loss: 0.6342 - val_accuracy: 0.5000 - val_loss: 0.7187
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.5000 - loss: 0.6297 - val_accuracy: 0.5000 - val_loss: 0.7205
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 0.5000 - loss: 0.6253 - val_accuracy: 0.5000 - val_loss: 0.7223
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 0.7500 - loss: 0.6209 - val_accuracy: 0.5000 - val_loss: 0.7240
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.7500 - loss: 0.6165 - val_accuracy: 0.5000 - val_loss: 0.7257
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 0.7500 - loss: 0.6121 - val_accuracy: 0.5000 - val_loss: 0.7274
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.7500 - loss: 0.6078 - val_accuracy: 0.5000 - val_loss: 0.7291
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - accuracy: 0.7500 - loss: 0.6035 - val_accuracy: 0.5000 - val_loss: 0.7307
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 0.7500 - loss: 0.5990 - val_accuracy: 0.5000 - val_loss: 0.7326
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 0.7500 - loss: 0.5945 - val_accuracy: 0.5000 - val_loss: 0.7347
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - accuracy: 0.7500 - loss: 0.5899 - val_accuracy: 0.5000 - val_loss: 0.7370
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - accuracy: 0.7500 - loss: 0.5852 - val_accuracy: 0.5000 - val_loss: 0.7394
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - accuracy: 0.7500 - loss: 0.5805 - val_accuracy: 0.5000 - val_loss: 0.7418
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - accuracy: 0.7500 - loss: 0.5758 - val_accuracy: 0.5000 - val_loss: 0.7443
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - accuracy: 0.7500 - loss: 0.5711 - val_accuracy: 0.5000 - val_loss: 0.7469
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 0.7500 - loss: 0.5664 - val_accuracy: 0.5000 - val_loss: 0.7495
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.7500 - loss: 0.5618 - val_accuracy: 0.5000 - val_loss: 0.7522
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.7500 - loss: 0.5571 - val_accuracy: 0.5000 - val_loss: 0.7550
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.7500 - loss: 0.5524 - val_accuracy: 0.5000 - val_loss: 0.7579
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.7500 - loss: 0.5477 - val_accuracy: 0.5000 - val_loss: 0.7608
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.7500 - loss: 0.5431 - val_accuracy: 0.5000 - val_loss: 0.7638
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - accuracy: 0.7500 - loss: 0.5388 - val_accuracy: 0.5000 - val_loss: 0.7668
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.7500 - loss: 0.5345 - val_accuracy: 0.5000 - val_loss: 0.7697
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.7500 - loss: 0.5302 - val_accuracy: 0.5000 - val_loss: 0.7726
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.7500 - loss: 0.5260 - val_accuracy: 0.5000 - val_loss: 0.7755
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step - accuracy: 0.7500 - loss: 0.5218 - val_accuracy: 0.5000 - val_loss: 0.7783
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 0.7500 - loss: 0.5176 - val_accuracy: 0.5000 - val_loss: 0.7812
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.7500 - loss: 0.5133 - val_accuracy: 0.5000 - val_loss: 0.7841
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - accuracy: 0.7500 - loss: 0.5091 - val_accuracy: 0.5000 - val_loss: 0.7870
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.7500 - loss: 0.5049 - val_accuracy: 0.5000 - val_loss: 0.7900
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.7500 - loss: 0.5007 - val_accuracy: 0.5000 - val_loss: 0.7929
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - accuracy: 0.7500 - loss: 0.4965 - val_accuracy: 0.5000 - val_loss: 0.7960
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - accuracy: 0.7500 - loss: 0.4922 - val_accuracy: 0.5000 - val_loss: 0.7989
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.7500 - loss: 0.4881 - val_accuracy: 0.5000 - val_loss: 0.8018
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.7500 - loss: 0.4841 - val_accuracy: 0.5000 - val_loss: 0.8047
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.7500 - loss: 0.4800 - val_accuracy: 0.5000 - val_loss: 0.8075
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 0.7500 - loss: 0.4759 - val_accuracy: 0.5000 - val_loss: 0.8103
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.7500 - loss: 0.4718 - val_accuracy: 0.5000 - val_loss: 0.8131
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - accuracy: 0.7500 - loss: 0.4678 - val_accuracy: 0.5000 - val_loss: 0.8159
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - accuracy: 0.7500 - loss: 0.4638 - val_accuracy: 0.5000 - val_loss: 0.8186
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.7500 - loss: 0.4599 - val_accuracy: 0.5000 - val_loss: 0.8212
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.7500 - loss: 0.4559 - val_accuracy: 0.5000 - val_loss: 0.8239
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.7500 - loss: 0.4520 - val_accuracy: 0.5000 - val_loss: 0.8265
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.7500 - loss: 0.4482 - val_accuracy: 0.5000 - val_loss: 0.8291
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.7500 - loss: 0.4443 - val_accuracy: 0.5000 - val_loss: 0.8317
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.7500 - loss: 0.4404 - val_accuracy: 0.5000 - val_loss: 0.8342
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.7500 - loss: 0.4365 - val_accuracy: 0.5000 - val_loss: 0.8368
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.7500 - loss: 0.4326 - val_accuracy: 0.5000 - val_loss: 0.8394
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 0.8750 - loss: 0.4289 - val_accuracy: 0.5000 - val_loss: 0.8420
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.8750 - loss: 0.4252 - val_accuracy: 0.5000 - val_loss: 0.8446
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.8750 - loss: 0.4216 - val_accuracy: 0.5000 - val_loss: 0.8473
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - accuracy: 0.8750 - loss: 0.4179 - val_accuracy: 0.5000 - val_loss: 0.8501
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step - accuracy: 1.0000 - loss: 0.4142 - val_accuracy: 0.5000 - val_loss: 0.8530
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step - accuracy: 1.0000 - loss: 0.4108 - val_accuracy: 0.5000 - val_loss: 0.8557
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 319ms/step - accuracy: 1.0000 - loss: 0.4074 - val_accuracy: 0.5000 - val_loss: 0.8583
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 324ms/step - accuracy: 1.0000 - loss: 0.4040 - val_accuracy: 0.5000 - val_loss: 0.8610
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 1.0000 - loss: 0.4008 - val_accuracy: 0.5000 - val_loss: 0.8637
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - accuracy: 1.0000 - loss: 0.3975 - val_accuracy: 0.5000 - val_loss: 0.8665
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - accuracy: 1.0000 - loss: 0.3942 - val_accuracy: 0.5000 - val_loss: 0.8693
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - accuracy: 1.0000 - loss: 0.3909 - val_accuracy: 0.5000 - val_loss: 0.8723
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step - accuracy: 1.0000 - loss: 0.3877 - val_accuracy: 0.5000 - val_loss: 0.8754
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 321ms/step - accuracy: 1.0000 - loss: 0.3845 - val_accuracy: 0.5000 - val_loss: 0.8785
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step - accuracy: 1.0000 - loss: 0.3814 - val_accuracy: 0.5000 - val_loss: 0.8816
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 1.0000 - loss: 0.3783 - val_accuracy: 0.5000 - val_loss: 0.8847
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - accuracy: 1.0000 - loss: 0.3752 - val_accuracy: 0.5000 - val_loss: 0.8879
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - accuracy: 1.0000 - loss: 0.3722 - val_accuracy: 0.5000 - val_loss: 0.8912
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 1.0000 - loss: 0.3692 - val_accuracy: 0.5000 - val_loss: 0.8946
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 1.0000 - loss: 0.3662 - val_accuracy: 0.5000 - val_loss: 0.8980
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 1.0000 - loss: 0.3632 - val_accuracy: 0.5000 - val_loss: 0.9014

In [70]:
loss, accuracy = bank_model.evaluate(X_test_scaled, y_test)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.9014
Test Loss: 0.9014284610748291
Test Accuracy: 0.5

In [73]:
new_customer = pd.DataFrame({
"CreditScore": [720],
"Geography": ["France"],
"Gender": ["Male"],
"Age": [42],
"Balance": [62000],
"NumOfProducts": [1],
"EstimatedSalary": [55000]
})
# Encode and scale same as before
new_customer ["Gender"] = le. transform(new_customer ["Gender"])
new_customer = pd.get_dummies(new_customer, columns=["Geography"], drop_first=True)

# Add missing dummy columns
for col in [c for c in X.columns if c not in new_customer.columns]:
  new_customer [col] = 0

new_customer = new_customer [X.columns]
new_scaled = scaler.transform(new_customer)

# Predict
pred =bank_model.predict(new_scaled)
if pred[0][0] > 0.5:
  print("Customer will leave")

# same order

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step